Added `openFiltersMode` on `filter-navigator`
vtex-apps/search-result pull request #417
Opened 2020-09-04 17:02 UTC by iaronaraujo

#### What problem is this solving?

Add a prop to make it possible to only have one AvailableFilter open at the same time. Solves this issue https://github.com/vtex-apps/search-result/issues/381 and is based on this PR https://github.com/vtex-apps/search-result/pull/397
The credit of this PR should go to @felipeireslan since he created the PR this was based on.

#### How to test it?

[Workspace](https://iaronaraujo--storecomponents.myvtex.com/apparel---accessories/clothing/)

#### Screenshots or example usage:

![Sep-04-2020 14-00-24](https://user-images.githubusercontent.com/8443580/92267494-20816c00-eeb7-11ea-8b1a-d89114ac6863.gif)

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

2020-09-04 17:05 UTC, klzns requested changes

2020-09-04 17:05 UTC, klzns commented on docs/README.md
> +| `openFiltersMode`    | `Enum` | Dictates how many filters can be open at the same time. It is possible to have many open at once (`MANY`) or just one (`ONE`). Notice that if `ONE` is selected, the
```suggestion
| `openFiltersMode`    | `Enum` | Dictates how many filters can be open at the same time. It is possible to have many open at once (`many`) or just one (`one`). Notice that if `one` is selected, the filters will begin collapsed, regardless of what is passed to `initiallyCollapsed` | `many` |
```

2020-09-04 17:05 UTC, klzns commented on react/FilterNavigator.js
> +  openFiltersMode = 'MANY',
```suggestion
  openFiltersMode = 'many',
```

2020-09-04 17:05 UTC, klzns commented on react/components/AvailableFilters.js
> +  openFiltersMode = 'MANY',
```suggestion
  openFiltersMode = 'many',
```

2020-09-04 17:05 UTC, klzns commented on react/components/FilterOptionTemplate.js
> +  const isOpen = openFiltersMode === 'MANY' ? open : lastOpenFilter === title
```suggestion
  const isOpen = openFiltersMode === 'many' ? open : lastOpenFilter === title
```

2020-09-04 17:05 UTC, klzns commented on react/components/FilterOptionTemplate.js
> +    }
```suggestion
    if (openFiltersMode === 'many') {
      setOpen(!open)
      return
    }
    if (openFiltersMode === 'one') {
      setLastOpenFilter(lastOpenFilter === title ? null : title)
      return
    }
    
    console.error(
        `Invalid openFiltersMode value: ${openFiltersMode}\nCheck the documentation for the values available`
      )
```

2020-09-10 03:33 UTC, guerreirobeatriz requested changes

2020-09-10 03:33 UTC, guerreirobeatriz commented on docs/README.md
> +| `openFiltersMode`    | `Enum` | Dictates how many filters can be open at the same time. It is possible to have many open at once (`many`) or just one (`one`). Notice that if `one` is selected, the
```suggestion
| `openFiltersMode`    | `Enum` | Defines how many filter categories can be opened at the same time on the Filter Navigator component. Possible values are: `many` (more than one filter category can be opened at the same time) and `one` (only one filter category can be opened). Notice that if `one` is declared, the filters will always be collapsed before user interaction, regardless of what is passed to the `initiallyCollapsed` prop. | `many` |
```

2020-09-10 12:10 UTC, victorhmp approved these changes

2020-09-10 12:10 UTC, victorhmp commented on react/components/AvailableFilters.js
> +  openFiltersMode = 'many',
Just a suggestion, but how about calling this mode `multiple` instead of `many`?

2020-09-14 14:31 UTC, ricardo7634234 commented
Good morning guys, do we have an update? What´s next?

2020-09-14 14:34 UTC, iaronaraujo commented
Hi @ricardo7634234 !  After some of the most recent changes to this app, this solution stopped working, so I am still investigating how to make this work properly!

2020-09-14 18:59 UTC, klzns approved these changes

2020-09-14 19:09 UTC, guerreirobeatriz approved these changes

2020-09-14 19:20 UTC, merged