Fix search title with percentage
vtex-apps/search-result pull request #441
Opened 2020-10-23 18:18 UTC by thalytafabrine

#### What problem is this solving?

When the search title had a percentage symbol (`%`) the SearchTitle component was not displayed due to an error when trying to run `decodeURI(title)`

[Issue](https://github.com/vtex-apps/store-discussion/issues/442)

#### How to test it?

[Before](https://acctglobal.myvtex.com/141?map=productClusterIds)

[Workspace](https://raissateste--acctglobal.myvtex.com/141?map=productClusterIds)

#### Screenshots or example usage:

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2020-10-23 18:25 UTC, klzns approved these changes

2020-11-05 18:18 UTC, icazevedo requested changes

2020-11-05 18:18 UTC, icazevedo commented on react/SearchTitle.js
>    if (!title) {
I think this check should be done before the `useMemo` hook. Calling `decodeURI` on `null` or `undefined` returns a string, so this makes this condition unreachable. It also deviates from the previous behavior.

2020-11-05 18:20 UTC, icazevedo commented on react/SearchTitle.js
>    if (!title) {
Ooops, my bad! I thought you were using decodedTitle 😅 My bad!

2020-11-05 18:21 UTC, icazevedo approved these changes

2020-11-05 20:58 UTC, merged