Add support for 'OrderByCollection' option to 'orderBy'
vtex-apps/search-result pull request #442
Opened 2020-10-27 20:16 UTC by victorhmp

#### What problem is this solving?

#### How to test it?

[Workspace](Link goes here!)

#### Screenshots or example usage:

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2020-10-28 18:24 UTC, klzns requested changes
Changing the translation key is a breaking change, please revert that change

2020-11-04 14:09 UTC, kaisermann commented on react/constants/propTypes.js
> +   * e.g: { department: 'electronics', category: 'smartphones' }
:SATISFACTION:

2020-11-04 14:09 UTC, kaisermann approved these changes

2020-11-04 14:47 UTC, icazevedo approved these changes

2020-11-04 18:18 UTC, guerreirobeatriz approved these changes

2020-11-05 16:24 UTC, merged