add totalProducts prop
vtex-apps/search-result pull request #445
Opened 2020-11-03 20:09 UTC by hiagolcm

#### What problem is this solving?

1. Add the `totalProductsOnMobileProp` that allows showing the total number of products on the filter side bar.

![image](https://user-images.githubusercontent.com/40380674/98033982-0c91b200-1df5-11eb-9e70-37068c9ef428.png)

2. `showFacetQuantity` now works on mobile

![image](https://user-images.githubusercontent.com/40380674/98035294-0b618480-1df7-11eb-92a9-f0338d664ad1.png)

#### How to test it?

[Workspace](https://totalproducts--storecomponents.myvtex.com/)

2020-11-03 20:14 UTC, klzns requested changes

2020-11-03 20:14 UTC, klzns commented on react/components/FilterSidebar.js
> +              className={`${handles.filterTotalProducts} w-100 flex flex-grow-1 items-center justify-center pre t-action--small`}
It's not an action, so I suggest to change to something more semantic
https://styleguide.vtex.com/#/Styles?id=section-typography

```suggestion
              className={`${handles.filterTotalProducts} w-100 flex flex-grow-1 items-center justify-center pre t-small`}
```

2020-11-04 18:29 UTC, guerreirobeatriz requested changes

2020-11-04 18:29 UTC, guerreirobeatriz commented on docs/README.md
> +| `totalProductsOnMobile` | `Enum` | Whether the total number of products will be visible on mobile (`"show"`) or not (`"hide"`). | `"hide"` |
```suggestion
| `totalProductsOnMobile` | `enum` | Whether the Filter Navigator should display the total number of products on mobile devices  (`show`) or not (`hide`). | `hide` |
```

2020-11-06 13:49 UTC, icazevedo approved these changes

2020-11-09 18:51 UTC, klzns approved these changes

2020-11-10 13:13 UTC, guerreirobeatriz approved these changes

2020-11-11 11:23 UTC, merged