productCount class
vtex-apps/search-result pull request #486
Opened 2021-01-28 11:03 UTC by khrizzcristian

#### What problem is this solving?
Allows users to stylize the number of products in a category.

#### How to test it?
Workspace

[Workspace](https://longo--diverta.myvtex.com/carti)

#### Screenshots or example usage:
![a](https://user-images.githubusercontent.com/43498488/106129711-2bd87b00-6169-11eb-8da5-1ca740b0b95b.jpg)

2021-02-02 16:15 UTC, hiagolcm requested changes

2021-02-02 16:15 UTC, hiagolcm commented on react/components/FacetItem.js
> +    <div>
I would prefer to use a Fragment to avoid breaking changes

2021-02-16 08:02 UTC, vtexdaniel approved these changes

2021-02-24 14:06 UTC, hiagolcm approved these changes

2021-02-24 14:12 UTC, hiagolcm approved these changes

2021-02-24 14:48 UTC, georgebrindeiro approved these changes
LGTM

2021-02-24 14:50 UTC, merged