adding prop "phone" to disply filter like on mobile even if you are on desktop
vtex-apps/search-result pull request #515
Opened 2021-05-25 10:19 UTC by GabiDanciu

I need a prop that renders filter-navigator like on mobile even if the resolution is desktop

https://category--joythestore.myvtex.com/womenswear/dresses

![image](https://user-images.githubusercontent.com/65282860/119481763-c03f9c80-bd5b-11eb-96f9-6649f0c9af49.png)

2021-05-31 18:59 UTC, victorhmp approved these changes
LGTM

2021-05-31 18:59 UTC, victorhmp commented on CHANGELOG.md
> +- adding `phone` type on prop `layout` to the `FilterNavigator`.
```suggestion
### Added
- `phone` option to the `layout` prop  from `FilterNavigator` component.
```

2021-06-02 12:28 UTC, thalytafabrine commented on react/FilterNavigator.js
> +    !isMobile && layout === LAYOUT_TYPES.phone || isMobile && layout === LAYOUT_TYPES.phone
I think you can simplify it like this:
```suggestion
    layout === LAYOUT_TYPES.phone
```

2021-06-02 20:16 UTC, icazevedo requested changes

2021-06-02 20:16 UTC, icazevedo commented on react/FilterNavigator.js
> +    !isMobile && layout === LAYOUT_TYPES.phone || isMobile && layout === LAYOUT_TYPES.phone
I agree! You should do that.

2021-06-02 20:56 UTC, GabiDanciu commented on react/FilterNavigator.js
> +    !isMobile && layout === LAYOUT_TYPES.phone || isMobile && layout === LAYOUT_TYPES.phone
Done. Thanks for suggestions :D

2021-06-02 21:04 UTC, thalytafabrine approved these changes

2021-06-04 18:33 UTC, icazevedo requested changes
Could you please fix the lint issues you've introduced on you last commit? thanks

2021-06-09 19:44 UTC, icazevedo approved these changes

2021-06-21 19:00 UTC, victorhmp approved these changes

2021-06-29 17:46 UTC, igorbrasileiro commented on docs/README.md
> +| `layout`  | `Enum` | Whether the Filter Navigator layout should be responsive (`responsive`) or not (`desktop`, `phone`). You may use`phone` when mobile layout is needed on the desktop resolution a
```suggestion
| `layout`  | `Enum` | Whether the Filter Navigator layout should be responsive (`responsive`) or not (`desktop`, `phone`). You may use `phone` when the mobile layout is needed on the desktop resolution and `desktop` when the Filter Navigator was configured to be displayed in a [drawer](https://vtex.io/docs/components/content-blocks/vtex.store-drawer@0.9.0). | `responsive`  |
```

2021-06-29 17:46 UTC, igorbrasileiro approved these changes

2021-06-29 18:00 UTC, merged