Fix documentation
vtex-apps/search-result pull request #552
Opened 2021-11-08 12:23 UTC by thalytafabrine

#### What problem is this solving?

#### How to test it?

[Workspace](Link goes here!)

#### Screenshots or example usage:

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2021-12-14 17:23 UTC, hiagolcm approved these changes

2022-01-05 13:46 UTC, karenkrieger requested changes

2022-01-05 13:46 UTC, karenkrieger commented on docs/README.md
> +| value      | string | Value that will be sent for ordering in the API. Must be in the format `{specification key}:{asc|desc}`. For example: `"size:desc"` or `"priceByUnit:asc"`. | `undefined` |
```suggestion
| value      | string | Value that will be sent for ordering in the API. It must be in the format `{specification key}:{asc|desc}`. For example: `"size:desc"` or `"priceByUnit:asc"`. | `undefined` |
```

2022-01-05 14:30 UTC, karenkrieger approved these changes
Documentation LGTM

2022-01-05 14:42 UTC, merged